### ISSUE TITLE
Multiple instances of the same parameter in sqlite statement fail

### ISSUE THREAD

**Issue by KMWenyon** [ellisnet/Portable.Data.Sqlite#4]
I have a sqlite statement with the same parameter name (@TimeNow) several times in the statement (shown below), I get a binding exception.  What is happening when the sqlite statement is parsed it adds the parameter name several times and the value once.

REPIOSITORY CODE:
...
// Create a new sqlite command with the command text and sqlite ado database connection.
   using (var sqliteCommand = new SqliteCommand(XCommands.GetAllWidgetsVisible, sqliteAdoConnection))
    {
         // Add the parameters and values.
         sqliteCommand.Parameters.AddWithValue(ParameterNames.Limit, take);
         sqliteCommand.Parameters.AddWithValue(ParameterNames.Skip, skip);
         var todayDateParm = sqliteCommand.Parameters.Add(ParameterNames.TodayDate, DbType.Date);
         todayDateParm.Value = todayDate;

```
     if (!includeHidden)
         sqliteCommand.Parameters.AddWithValue(ParameterNames.TimeNow, DateTime.Now);

      // Execute the command and return the result sets.
      using (var sqliteDataReader = sqliteCommand.ExecuteReader())
      {
           // Read the next row from the result set.
           while (sqliteDataReader.Read())
           {
               // Id, Name, Count(*) As ChecklistCount
               var id = sqliteDataReader.GetInt32("Id");
               var name = sqliteDataReader.IsDBNull("Name") ? null : sqliteDataReader.GetString("Name");
               var checklistCount = sqliteDataReader.GetInt32("ChecklistCount");
               departmentModelListRetVal.Add(newDepartmentModel(id, name, checklistCount));
           }
      }
 }
```

...

SQLITE COMMAND:
            @"SELECT D.Id, D.Name, Count(*) As ChecklistCount
                FROM Departments AS D
          INNER JOIN CheckListDepartments AS CD ON D.Id = CD.DepartmentId
          INNER JOIN CheckListInstances AS CLI ON CD.CheckListId = CLI.CheckListId
                 AND CLI.BusinessDate = @TodayDate AND CLI.IsTemplate = 0 AND CLI.IsCompleted = 0
                 AND ( (StartTime IS NULL AND EndTime IS NULL)
                   OR  (StartTime IS NOT NULL AND EndTime IS NULL AND @TimeNow > StartTime)
                   OR  (StartTime IS NOT NULL AND EndTime IS NOT NULL AND @TimeNow BETWEEN StartTime AND EndTime)
                   OR  (StartTime IS NULL AND EndTime IS NOT NULL AND @TimeNow < EndTime) )
          GROUP BY D.Id, D.Name
          ORDER BY D.Name COLLATE NOCASE 
          LIMIT @Limit OFFSET @Skip";

ParmName         ParmValue
@TodayDate    2015/02/05
@TimeNow      2015/02/05 17:02:35
@TimeNow      NULL
@TimeNow      NULL
@Limit        1000
@Skip         0

Exception of type 'Portable.Data.Sqlite.SqliteException' was thrown.

Portable.Data.Sqlite
   at Portable.Data.Sqlite.SqliteStatement.BindParameter(Int32 index, SqliteParameter param)
   at Portable.Data.Sqlite.SqliteStatement.BindParameters()
   at Portable.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Portable.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Portable.Data.Sqlite.SqliteDataReader.NextResult()
   at Portable.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, Boolean setRowId, CommandBehavior behave, IObjectCryptEngine cryptEngine)
   at Portable.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave, IObjectCryptEngine cryptEngine)
   at Portable.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Portable.Data.Sqlite.SqliteCommand.ExecuteReader()
   at SureCheck.Mobile.Shared.Sqlite.Repositories.DepartmentsRepository.GetAllDepartmentModels(DateTime todayDate, Int32 take, Int32 skip, Boolean includeHidden)

**Comment by ellisnet** [comment]
Here is a simpler example of the problem.

The following code works fine:
 string word = "Hello";

sql = "SELECT * FROM [myTableName] WHERE [FirstWord] = @word;";
using (var myCommand = new SqliteCommand(sql, dbConnection)) {
    myCommand.Parameters.Add(new SqliteParameter("@word", word));
    dbConnection.SafeOpen();
    using (SqliteDataReader myReader = myCommand.ExecuteReader()) {
        while (myReader.Read()) {
            int rowId = myReader.GetInt32("Id");
            string firstWord = myReader["FirstWord"].ToString() ?? "";
            string lastWord = myReader.GetString("SecondWord") ?? "";
            Debug.WriteLine("Row# {0} = {1} {2}!", rowId, firstWord, lastWord); 
        }
    }
}

BUT the following version fails with the Portable.Data.Sqlite.SqliteStatement.BindParameter error shown above.

string word = "Hello";

sql = "SELECT * FROM [myTableName] WHERE [FirstWord] = @word OR [SecondWord] = @word;";
using (var myCommand = new SqliteCommand(sql, dbConnection)) {
    myCommand.Parameters.Add(new SqliteParameter("@word", word));
    dbConnection.SafeOpen();
    using (SqliteDataReader myReader = myCommand.ExecuteReader()) {
        while (myReader.Read()) {
            int rowId = myReader.GetInt32("Id");
            string firstWord = myReader["FirstWord"].ToString() ?? "";
            string lastWord = myReader.GetString("SecondWord") ?? "";
            Debug.WriteLine("Row# {0} = {1} {2}!", rowId, firstWord, lastWord);
        }
    }
}

This is because the parameter @word appears multiple times in the SQL SELECT query.

As of 2/18/2015, this bug is being actively investigated and a fix is expected soon.
Jeremy

**Comment by ellisnet** [comment]
I have committed a code change to the repository that I believe will resolve this issue.  I have much more testing to do to make sure that there are no ill side-effects.  Then I will release an updated NuGet package - version 1.1.3 - which will contain the fix.

**Comment by wenyonk** [comment]
Jeremy:

 

THANK YOU!

 

Ken

**Comment by wenyonk** [comment]
Jeremy, I was testing the fixes recent posted for this issue.  I found a breaking change (this previously worked) with a single parameter in the following statement:

sqliteCommand.Parameters.AddWithValue(ParameterNames.Pin, pin);
...
using (var sqliteDataReader = sqliteCommand.ExecuteReader())
{
    ...
}

SELECT Id, Revision, FirstName, LastName, IsAdmin, IsAllDepartments, LocationId
                FROM Users 
               WHERE Pin = @Pin;

              SELECT UserId, DepartmentId 
                FROM UserDepartments                 
                JOIN Users AS U ON U.[Pin] = @Pin
               WHERE UserId = U.[Id]

The statement above is in a single command and returns two result sets and I believe the second select statement does have the @Pin parameter value.

**Comment by wenyonk** [comment]
As a workaround, Also tried to add the same parameter 3 times (from my original example) with the original code also caused an exception

**Comment by wenyonk** [comment]
Jeremy:

I have written you several emails since you last checkin, I have called you twice, why are you NOT responding or providing some type of update on this issue?

**Comment by ellisnet** [comment]
I will be testing your code with the new [SimpleAdo.Sqlite](https://github.com/ellisnet/SimpleAdo) library; to see if that library has this same problem.

**Comment by ellisnet** [comment]
No ongoing maintenance on this repo.
